spring:
  profiles: s1
  application:
    name: user-service
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}