server:
  port: 9090

spring:
  application:
    name: accelerator

  datasource:
    url: jdbc:sqlite:/Users/shenlan/mycloud.sqlite
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC

  mvc:
    converters:
      preferred-json-mapper: gson

  gson:
    date-format: yyyy-MM-dd HH:mm:ss

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    banner: false

datasource:
  exec-type: normal