server:
  port: 9090

spring:
  application:
    name: accelerator

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://10.68.165.163:3306/mycloud
    url: jdbc:mariadb://127.0.0.1:3306/mycloud
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

  http:
    converters:
      preferred-json-mapper: gson

  gson:
    date-format: yyyy-MM-dd HH:mm:ss