server:
  port: 9090

spring:
  application:
    name: accelerator

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\Users\shenlan\mycloud.sqlite
    type: com.zaxxer.hikari.HikariDataSource

  mvc:
    converters:
      preferred-json-mapper: gson

  gson:
    date-format: yyyy-MM-dd HH:mm:ss

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    banner: false